FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y \
    sqlite3 \
    libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000

CMD ["bash", "-c", "python create_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"]
